### PR TITLE
Create citation file

### PR DESCRIPTION
**Pull request by kelly-sovacool**
## Changes

- Create a citation.cff file.
- We will need to update it with the all-versions DOI from Zenodo after the next release.

## Issues

NA

## PR Checklist

(~Strikethrough~ any points that are not applicable.)

- [x] This comment contains a description of changes with justifications, with any relevant issues linked.
- ~[ ] Update docs if there are any API changes.~
- [x] Update `CHANGELOG.md` with a short description of any user-facing changes and reference the PR number. Guidelines: https://keepachangelog.com/en/1.1.0/

### CODE REVIEW

**Comment by kelly-sovacool** [comment]
@kopardev should any of the contributors who are no longer part of CCBR also be included as co-authors?

**Comment by kelly-sovacool** [comment]
CFF supports an affiliations field (see [schema guide](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)), which can consist of a string. @kopardev Can you confirm what our affiliations should be listed as? 

Note: cff only supports one affiliation per author, but allowing a list of affiliations is an open request: https://github.com/citation-file-format/citation-file-format/issues/268

**Comment by kelly-sovacool** [comment]
@kopardev this should be ready to merge now

**Review by slsevilla — APPROVED** [review]
looks good!

**Pull request merged**
